##############################
#### WINDOWS - WORKSPACES ####
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
windowrule = border_size 0, rounding 0, match:float 0, match:workspace w[tv1]
windowrule = border_size 0, rounding 0, match:float 0, match:workspace f[1]

# Float Rule
windowrule = rounding 12, match:float on
windowrule = float on, center on, size 850 500,  match:class .*(Alacritty|pavucontrol|waypaper|Nautilus|hyprland-share-picker|xdg-desktop-portal-gtk)$

windowrule = float on, center on, size 542 640, match:class .*(com.github.adw-network)$

# Fullscreen Rule
windowrule = fullscreen on, match:class Waydroid

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class .*

# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0
